security:
  auth:
    cookie:
      same-site:
        enabled: false
      token:
        lifeMin: 30
        secret: null
      superUserIds: ['abc']
  responseHeaders:
    HSTS:
      max-age: 31536000
      includeSubDomains: true
    X-XSS-Protection: 1; mode=block # 0: Filter disabled / 1: Filter enabled / mode=block -> Block all page when attacked
    X-Content-Type-Options: true
    Content-Security-Policy: base-uri 'self'
  container:
    host: localhost
    ports:
      http: 8081
      https: 8082
    keystore:
      location: keystore.jks
      password: optimize
    status:
      connections:
        max: 10
    accessUrl: null
    
engines:
  'camunda-bpm':
    name: default
    defaultTenant:
      id: null
      name: null
    rest: "http://localhost:8081/engine-rest"
    importEnabled: true
    eventImportEnabled: false
    authentication:
      enabled: false
      password: ''
      user: ''
    webapps:
      endpoint: "http://localhost:8081/camunda"
      enabled: true

engine-commons:
  connection:
    timeout: 30
  read:
    timeout: 30

import:
  data:
    activity-instance:
      maxPageSize: 10000
    incident:
      maxPageSize: 10000
    process-definition-xml:
      maxPageSize: 2
    process-definition:
      maxPageSize: 10000
    process-instance:
      maxPageSize: 10000
    variable:
      maxPageSize: 10000
    user-task-instance:
      maxPageSize: 10000
    identity-link-log:
      maxPageSize: 10000
    decision-definition-xml:
      maxPageSize: 2
    decision-definition:
      maxPageSize: 10000
    decision-instance:
      maxPageSize: 10000
    tenant:
      maxPageSize: 10000
    group:
      maxPageSize: 10000
    authorization:
      maxPageSize: 10000
    dmn:
      enabled: true
    user-task-worker:
      enabled: true
      metadata:
        includeUserMetaData: true
        cronTrigger: '0 */3 * * *'
        maxPageSize: 10000
        maxEntryLimit: 100000
  elasticsearchJobExecutorThreadCount: 1
  elasticsearchJobExecutorQueueSize: 5
  handler:
    backoff:
      initial: 1000
      max: 30
  importIndexStorageIntervalInSec: 10
  currentTimeBackoffMilliseconds: 10000
  identitySync:
    includeUserMetaData: true
    cronTrigger: '0 */2 * * *'
    maxPageSize: 10000
    maxEntryLimit: 100000

es:
  connection:
    timeout: 10000
    nodes:
        host: 'localhost'
        httpPort: 9200
    proxy:
      enabled: false
      host: null
      port: null
      sslEnabled: false
  security:
    username: null
    password: null
    ssl:
      certificate: null
      certificate_authorities: []
      enabled: false
  scrollTimeout: 60000
  settings:
    aggregationBucketLimit: 1000
    index:
      prefix: 'optimize'
      number_of_replicas: 1
      number_of_shards: 5
      refresh_interval: 2s
      nested_documents_limit: 10000

plugin:
  directory: './plugin'
  variableImport:
    basePackages: []
  engineRestFilter:
    basePackages: []
  authenticationExtractor:
    basePackages: []
  decisionInputImport:
    basePackages: []
  decisionOutputImport:
    basePackages: []

serialization:
  engineDateFormat: yyyy-MM-dd HH:mm:ss#yyyy-MM-dd'T'HH:mm:ss.SSSZ

alerting:
  quartz:
    jobStore: 'org.quartz.simpl.RAMJobStore'

email:
  enabled: false
  address: ''
  hostname: ''
  port: 587
  authentication:
    enabled: true
    username: ''
    password: ''
    securityProtocol: 'NONE'

export:
  csv:
    limit: 1000

sharing:
  enabled: true

historyCleanup:
  cronTrigger: '0 1 * * *'
  ttl: 'P2Y'
  processDataCleanup:
    enabled: false
    cleanupMode: 'all'
    batchSize: 10000
    perProcessDefinitionConfig:
  decisionDataCleanup:
    enabled: false
    perDecisionDefinitionConfig:
  ingestedEventCleanup:
    enabled: false

locales:
  availableLocales: ['en', 'de']
  fallbackLocale: 'en'

ui:
  header:
    textColor: 'dark'
    pathToLogoIcon: 'logo/camunda_icon.svg'
    backgroundColor: '#FFFFFF'

eventBasedProcess:
  authorizedUserIds: ['abc']
  authorizedGroupIds: ['abc']
  eventImport:
    enabled: false 
    maxPageSize: 10000
  eventIngestion:
    accessToken: null
    maxBatchRequestBytes: 10485760
    maxRequests: 5
  eventIndexRollover:
    scheduleIntervalInMinutes: 10
    maxIndexSizeGB: 50

telemetry:
  initializeTelemetry: false